baseurl = "https://wews.co/"
title = "a blog of spaghettiwews"
author = "Welington Maposa"
canonifyurls = true
languagecode = "en"
theme = "hugo-jessie"
enableGitInfo = true
paginate=50

[params]
  tagline = "there is yet insufficient data for a meaningful answer"
  author = "Welington Maposa"

[menu]
    [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 10

    #[[menu.main]]
    #name = "Projects"
    #url = "/projects/"
    #weight = 50

    [[menu.main]]
    name = "Knowledgebase"
    url = "/kb/"
    weight = 50    

    #[[menu.social]]
    #name = "LinkedIn"
    #url = "https://www.linkedin.com/"
    #pre = "/static/icons/linkedin.svg"
    #weight = 20

    [[menu.social]]
    name = "Github"
    url = "https://www.github.com/spaghettiwews"
    pre = "/static/icons/github.svg"
    weight = 10

    [[menu.social]]
    name = "RSS"
    url = "https://wews.co/index.xml"
    pre = "/static/icons/rss.svg"
    weight = 30
    
    [[menu.footer]]
    name = "Attribution"
    url = "/attribution/"
    weight = 10

[permalinks]
  post = "/:year/:month/:day/:filename/"
  page = "/:title/"
  kb = "/kb/:title/"
